#! /usr/bin/env bash

echo 'Getting wiki docs'
mkdir src/main/resources/wiki-data
wget -O wiki-subset.tar.gz https://www.dropbox.com/s/nzlb96ejt3lhd7g/wiki-subset-20140602.tar.gz?dl=0
tar -xzvf wiki-subset.tar.gz -C src/main/resources/wiki-data
rm -f wiki-subset.tar.gz
rm -f src/main/resources/wiki-data/._*
